### ISSUE TITLE
Unexpected server response causes uncaught exception

### ISSUE THREAD

**Issue by normen** [MeisterTR/ioBroker.landroid-s#20]
I am using mqttCloud.js from this plugin for my own homebridge-landroid plugin and I am getting the error below since today because the server seems to respond with "Not Found".

The iOS app to control the mowers seems to work though.. Maybe they changed something server side?

```
Apr 08 01:41:31 homebridge homebridge[13190]: SyntaxError: Unexpected token N in JSON at position 0
Apr 08 01:41:31 homebridge homebridge[13190]:     at JSON.parse (<anonymous>)
Apr 08 01:41:31 homebridge homebridge[13190]:     at IncomingMessage.<anonymous> (/home/pi/npm-code/homebridge-landroid/node_modules/iobroker.landroid-s/lib/mqttCloud.js:278:49)
Apr 08 01:41:31 homebridge homebridge[13190]:     at IncomingMessage.emit (events.js:194:15)
Apr 08 01:41:31 homebridge homebridge[13190]:     at endReadableNT (_stream_readable.js:1125:12)
Apr 08 01:41:31 homebridge homebridge[13190]:     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by MeisterTR** [comment]
Yes they changed the server, but i have already the new api, i need a day to fix

**Comment by MeisterTR** [comment]
done

**Comment by normen** [comment]
Thanks, that was quick! And thanks for the plugin in general! :)
