### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by kaefert** [MeisterTR/ioBroker.landroid-s#25]
This adapter was working for me last season, but throws errors now:

```
host.myHost1	2019-04-28 10:55:00.703	error	instance system.adapter.landroid-s.0 terminated with code 0 (OK)
landroid-s.0	2019-04-28 10:55:00.683	info	terminating
landroid-s.0	2019-04-28 10:55:00.451	info	starting. Version 2.5.5 in path/iobroker/node_modules/iobroker.landroid-s, node: v4.8.4
landroid-s.0	2019-04-28 10:55:00.173	error	at Object.Module._extensions..js (module.js:416:10)
landroid-s.0	2019-04-28 10:55:00.173	error	at Module._compile (module.js:409:26)
landroid-s.0	2019-04-28 10:55:00.173	error	at Object. (path/iobroker/node_modules/iobroker.landroid-s/main.js:10:17)
landroid-s.0	2019-04-28 10:55:00.173	error	at require (internal/module.js:12:17)
landroid-s.0	2019-04-28 10:55:00.173	error	at Module.require (module.js:353:17)
landroid-s.0	2019-04-28 10:55:00.173	error	at Function.Module._load (module.js:300:12)
landroid-s.0	2019-04-28 10:55:00.173	error	at Module.load (module.js:343:32)
landroid-s.0	2019-04-28 10:55:00.173	error	at Object.Module._extensions..js (module.js:416:10)
landroid-s.0	2019-04-28 10:55:00.173	error	at Module._compile (module.js:373:25)
landroid-s.0	2019-04-28 10:55:00.173	error	at exports.runInThisContext (vm.js:53:16)
landroid-s.0	2019-04-28 10:55:00.173	error	SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
landroid-s.0	2019-04-28 10:55:00.156	error	uncaught exception: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
host.myHost1	2019-04-28 10:54:58.995	info	instance system.adapter.landroid-s.0 started with pid 30325
host.myHost1	2019-04-28 10:54:28.985	info	Restart adapter system.adapter.landroid-s.0 because enabled
```

**Comment by MeisterTR** [comment]
please update node to min 6.x.x  better 8.x.x node 4 is not supported

**Comment by kaefert** [comment]
thanks! Updated to the current LTS release node-v10.15.3-linux-x64 restarted iobroker and now it works!
